<?php

/**
 * @var string                      $title              title of this module
 * @var Fisharebest\Webtrees\Tree   $tree
 * @var string                      $imprintHead1       main title of this page
 * @var string                      $imprintHead2       subtitle of this page
 * @var string                      $responsibleName    name of responsible person
 * @var string                      $street
 * @var string                      $city
 * @var string                      $phoneLabel
 * @var string                      $phone
 * @var string                      $faxLabel
 * @var string                      $fax
 * @var string                      $emailLabel
 * @var string                      $email
 * @var string                      $vatNumberLabel
 * @var string                      $vatNumber
 * @var array                       $contactLinks
 * @var string                      $img                complete html image link for gravatar
 */

?>
<h2><?= e($title) ?></h2>
<p>&nbsp;</p>
<h4><?= $imprintHead1 ?></h4>

<p><?= $imprintHead2 ?></p>

<table cellpadding="5">
    <tbody>
        <tr>
            <td valign="top"><?= $responsibleName ?></td>
            <?php if ($street <> ''): ?>
                <td><?= $street ?><br />
            <?php endif ?>
            <?php if ($city <> ''): ?>
                <?= $city ?></td>
            <?php endif ?>
        </tr>
        <?php if ($phone <> ''): ?>
            <tr>
                <td><?= $phoneLabel ?>:</td>
                <td><?= $phone ?></td>
            </tr>
        <?php endif ?>
        <?php if ($fax <> ''): ?>
            <tr>
                <td><?= $faxLabel ?>:</td>
                <td><?= $fax ?></td>
            </tr>
        <?php endif ?>
        <?php if ($email <> ''): ?>
            <tr>
                <td><?= $emailLabel ?>:</td>
                <td><?= $email ?></td>
            </tr>
        <?php endif ?>
        <?php if ($vatNumberLabel <> '' && $vatNumber <> ''): ?>
            <tr>
                <td><?= $vatNumberLabel ?>:</td>
                <td><?= $vatNumber ?></td>
            </tr>
        <?php endif ?>
    </tbody>
</table>
