<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

/**
 * @var string                  $title
 * @var string                  $description
 * @var string                  $responsibleFirst   first name(s) of responsible person
 * @var string                  $responsibleSurname surname(s) of responsible person
 * @var string                  $responsibleSex     gender of responsible person ('M', 'F', 'X')
 * @var string                  $organization       Club name or organization
 * @var string                  $street
 * @var string                  $city
 * @var string                  $phone
 * @var string                  $fax
 * @var string                  $email
 * @var string                  $simpleEmail
 * @var string                  $vatNumberLabel     Label like "VAT ID No." or other registration number label
 * @var string                  $vatNumber          VAT ID No. or other registration number
 */

?>

<?= view('components/breadcrumbs', [
        'links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>
<p><?= $description ?></p>

<div class="hh-imprint mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">

        <p></p>

        <h4><?= I18N::translate('Responsible person') . ' (' . I18N::translate('mandatory') . ')' ?></h4>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="responsibleFirst">
                <?= I18N::translate('First name(s)') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="responsibleFirst" name="responsibleFirst" type="text"
                       value="<?= $responsibleFirst ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="responsibleSurname">
                <?= I18N::translate('Surname(s)') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="responsibleSurname" name="responsibleSurname" type="text"
                       value="<?= $responsibleSurname ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="responsibleSex">
                <?= I18N::translate('Sex') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/radios', [
                    'id' => 'responsibleSex',
                    'name' => 'responsibleSex',
                    'selected' => $responsibleSex,
                    'options' => [
                        'M' => I18N::translate('male'),
                        'F' => I18N::translate('female'),
                        'X' => I18N::translate('other'),
                    ],
                ]) ?>
            </div>
        </div>

        <p></p>

        <h4><?= I18N::translate('Club or Organization') . ' (' . I18N::translate('optional') . ')'  ?></h4>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="organization">
                <?= I18N::translate('Name of club or organization') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="organization" name="organization" type="text" value="<?= $organization ?>">
            </div>
        </div>

        <p></p>

        <h4><?= I18N::translate('Address data') . ' (' . I18N::translate('mandatory') . ')'  ?></h4>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="street">
                <?= I18N::translate('Street name and house number') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="street" name="street" type="text" value="<?= $street ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="city">
                <?= I18N::translate('City including zip code') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="city" name="city" type="text" value="<?= $city ?>">
            </div>
        </div>

        <p></p>

        <h4><?= I18N::translate('Communication data') . ' (' .
                                    I18N::translate('Phone and eMail are mandatory') . ')'  ?></h4>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="phone">
                <?= I18N::translate('Phone number including country prefix, e.g. "+49 30 123456"') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="phone" name="phone" type="text" value="<?= $phone ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="fax">
                <?= I18N::translate('Fax number including country prefix, e.g. "+49 30 654321"') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="fax" name="fax" type="text" value="<?= $fax ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
                <?= I18N::translate('eMail address') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="email" name="email" type="text" value="<?= $email ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="simpleEmail">
                <?= I18N::translate('Should a simple eMail link be used?') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/checkbox', [
                    'label' => I18N::translate('(if not marked: subject and body of eMail are generated, too)'),
                    'id' => 'simpleEmail', 'name' => 'simpleEmail', 'checked' => $simpleEmail]) ?>
            </div>
        </div>

        <p></p>

        <h4><?= I18N::translate('Registration data') . ' (' . I18N::translate('optional') . ')'  ?></h4>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="vatNumberLabel">
                <?= I18N::translate('Label like VAT ID No. or other registration number label') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="vatNumberLabel" name="vatNumberLabel" type="text" value="<?= $vatNumberLabel ?>">
            </div>

            <label class="col-sm-3 col-form-label wt-page-options-label" for="vatNumber">
                <?= I18N::translate('Registration number') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="vatNumber" name="vatNumber" type="text" value="<?= $vatNumber ?>">
            </div>
        </div>

        <p></p>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>
